# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f16a3da972d0b9a2e7b5118df0bf57f786290c798a9fa7c31f66c5202aeafa31ced6c58f2d547a212cc263b647daacd0d9033d061f0d851121924b27783bf4f

test:
  secret_key_base: 41f0af0f7124f3c23ad6c836129f6af898cc2ee5069725ab63f8ddfd99eb41139c01843e93dfc31a29d3389063e1dc0833f08ea661d2c4c828c045ab236afdaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
